on: 
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'

name: Linux_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
        
        - name: 'Create secret file'
          uses: "finnp/create-file-action@master"
          env:
            FILE_NAME: "key.pem"
            FILE_DATA: ${{ secrets.KEY }}

        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/jenkins:actions
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/jenkins:actions 

        # execute remote commands
        - name: 'Deploy Containe to Azure VM'
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY }}
            port: ${{ secrets.PORT }}
            script: |
              docker login ${{ secrets.REGISTRY_LOGIN_SERVER }} -u${{ secrets.REGISTRY_USERNAME }} -p${{ secrets.REGISTRY_PASSWORD }}
              docker pull ${{ secrets.REGISTRY_LOGIN_SERVER }}/jenkins:actions
              docker run -d -p 8282:8080 --name JenkinsTest \
              -v /var/run/docker.sock:/var/run/docker.sock \
              --env JENKINS_ADMIN_ID="${JENKINS_ADMIN_ID}" \
              --env JENKINS_ADMIN_PASSWORD="${JENKINS_ADMIN_PASSWORD}" \
              --env JENKINS_RESERVE_URL="${JENKINS_RESERVE_URL}" \
              --env ACR_ADDR="${ACR_ADDR}" \
              --env ACR_PASS="${ACR_PASS}" \
              --env ACR_UID="${ACR_UID}" \
              --env DATASOURCE_PASSWORD="${DATASOURCE_PASSWORD}" \
              --env DATASOURCE_URL="${DATASOURCE_URL}" \
              --env DATASOURCE_USER="${DATASOURCE_USER}" \
              --env JWT_SECRET="${JWT_SECRET}" \
              --env MY_PASSWORD="${MY_PASSWORD}" \
              --env SUBSCRIPTION_ID="${SUBSCRIPTION_ID}" \
              --env VMIP="${VMIP}" \
              --env SSH_PRIVATE_FILE_PATH="${SSH_PRIVATE_FILE_PATH}" \
              --env CHAT_ID="${CHAT_ID}" \
              --env TELEGRAM_TOKEN="${TELEGRAM_TOKEN}" \
              --env SONAR_TOKEN="${SONAR_TOKEN}" \
              --env SONAR_SERVER="${SONAR_SERVER}" \
              --env NEXUS_SERVER="${NEXUS_SERVER}" \
              --env NEXUS_USER="${NEXUS_USER}" \
              --env NEXUS_PASSWORD="${NEXUS_PASSWORD}" \
              ${{ secrets.REGISTRY_LOGIN_SERVER }}/jenkins:actions