on: 
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'

name: Linux_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
        
        - name: 'Create secret file'
          run: |
            touch key.pem
            echo "${{ secrets.KEY }}" >> key.pem
            sudo chmod 400 key.pem
          shell: bash

        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
          run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/jenkins:actions
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/jenkins:actions 

        # execute remote commands
        - name: 'Deploy Container to Azure VM'
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY }}
            port: ${{ secrets.PORT }}
            script: |
              docker rm -f JenkinsTest
              docker login ${{ secrets.REGISTRY_LOGIN_SERVER }} -u${{ secrets.REGISTRY_USERNAME }} -p${{ secrets.REGISTRY_PASSWORD }}
              docker pull ${{ secrets.REGISTRY_LOGIN_SERVER }}/jenkins:actions
              docker run -d -p 8282:8080 --name JenkinsTest \
              -v /var/run/docker.sock:/var/run/docker.sock \
              --env JENKINS_ADMIN_ID="${{ secrets.JENKINS_ADMIN_ID }}" \
              --env JENKINS_ADMIN_PASSWORD="${{ secrets.JENKINS_ADMIN_PASSWOR }}" \
              --env JENKINS_RESERVE_URL="${{ secrets.JENKINS_RESERVE_URL }}" \
              --env ACR_ADDR="${{ secrets.REGISTRY_LOGIN_SERVER }}" \
              --env ACR_PASS="${{ secrets.REGISTRY_PASSWORD }}" \
              --env ACR_UID="${{ secrets.REGISTRY_USERNAME }}" \
              --env DATASOURCE_PASSWORD="${{ secrets.DATASOURCE_PASSWORD }}" \
              --env DATASOURCE_URL="${{ secrets.DATASOURCE_URL }}" \
              --env DATASOURCE_USER="${{ secrets.DATASOURCE_USER }}" \
              --env JWT_SECRET="${{ secrets.JWT_SECRET }}" \
              --env MY_PASSWORD="${{ secrets.MY_PASSWORD }}" \
              --env SUBSCRIPTION_ID="${{ secrets.SUBSCRIPTION_ID }}" \
              --env VMIP="${{ secrets.HOST }}" \
              --env SSH_PRIVA2TE_FILE_PATH="${{ secrets.SSH_PRIVATE_FILE_PATH }}" \
              --env CHAT_ID="${{ secrets.CHAT_ID }}" \
              --env TELEGRAM_TOKEN="${{ secrets.TELEGRAM_TOKEN }}" \
              --env SONAR_TOKEN="${{ secrets.SONAR_TOKEN }}" \
              --env SONAR_SERVER="${{ secrets.SONAR_SERVER }}" \
              --env NEXUS_SERVER="${{ secrets.NEXUS_SERVER }}" \
              --env NEXUS_USER="${{ secrets.NEXUS_USER }}" \
              --env NEXUS_PASSWORD="${{ secrets.NEXUS_PASSWORD }}" \
              ${{ secrets.REGISTRY_LOGIN_SERVER }}/jenkins:actions